# Generated by Django 4.2.3 on 2024-03-20 17:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companydetails", "0001_initial"),
        ("accounts", "0001_initial"),
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("middle_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("suffix", models.CharField(max_length=255, null=True)),
                ("display_name", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("mobile", models.CharField(max_length=255, null=True)),
                ("fax", models.CharField(max_length=255, null=True)),
                ("other", models.CharField(max_length=255, null=True)),
                ("website", models.CharField(max_length=255, null=True)),
                ("sub_customer", models.BooleanField(default=False)),
                ("street_address", models.TextField(null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("province", models.CharField(max_length=255, null=True)),
                ("postal_code", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                ("shipping_street_address", models.TextField(null=True)),
                ("shipping_city", models.CharField(max_length=255, null=True)),
                ("shipping_province", models.CharField(max_length=255, null=True)),
                ("shipping_postal_code", models.CharField(max_length=255, null=True)),
                ("shipping_country", models.CharField(max_length=255, null=True)),
                ("notes", models.TextField(null=True)),
                ("attachment", models.FileField(null=True, upload_to="attachments/")),
                (
                    "terms",
                    models.CharField(
                        choices=[
                            ("Due on receipt", "Due on receipt"),
                            ("Net 30", "Net 30"),
                            ("Net 60", "Net 60"),
                            ("Net 90", "Net 90"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "sales_form_delivery_options",
                    models.CharField(
                        choices=[
                            ("Print later", "Print later"),
                            ("Send later", "Send later"),
                            ("None", "None"),
                            ("Use company default", "Use company default"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "language_for_invoices",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("French", "French"),
                            ("Spanish", "Spanish"),
                            ("Italian", "Italian"),
                            ("Chinese (traditional)", "Chinese (traditional)"),
                            ("Portuguese (Brazil)", "Portuguese (Brazil)"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("sales_tax_registration", models.CharField(max_length=255, null=True)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("as_of", models.DateField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(null=True)),
                ("cc", models.TextField(null=True)),
                ("bcc", models.TextField(null=True)),
                ("send_later", models.BooleanField(default=False)),
                ("date", models.DateField(null=True)),
                ("attachment", models.FileField(null=True, upload_to="attachments/")),
                ("number", models.CharField(max_length=50, null=True)),
                ("billing_address", models.TextField(null=True)),
                ("message", models.CharField(max_length=255, null=True)),
                ("message_on_statement", models.CharField(max_length=255, null=True)),
                ("total_credit", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DelayedCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("number", models.CharField(max_length=50, null=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("memo", models.TextField(null=True)),
                ("attachment", models.FileField(null=True, upload_to="attachments/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DelayedCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("number", models.CharField(max_length=50, null=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("memo", models.TextField(null=True)),
                ("attachment", models.FileField(null=True, upload_to="attachments/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(null=True)),
                ("cc", models.TextField(null=True)),
                ("bcc", models.TextField(null=True)),
                ("send_later", models.BooleanField(default=False)),
                ("date", models.DateField(null=True)),
                ("attachment", models.FileField(null=True, upload_to="attachments/")),
                ("number", models.CharField(max_length=50, null=True)),
                ("billing_address", models.TextField(null=True)),
                ("message", models.CharField(max_length=255, null=True)),
                ("message_on_statement", models.CharField(max_length=255, null=True)),
                ("expiration_date", models.DateField(null=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Pending", "Pending"),
                            ("Rejected", "Rejected"),
                            ("Accepted", "Accepted"),
                            ("Closed", "Closed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(null=True)),
                ("cc", models.TextField(null=True)),
                ("bcc", models.TextField(null=True)),
                ("send_later", models.BooleanField(default=False)),
                ("date", models.DateField(null=True)),
                ("attachment", models.FileField(null=True, upload_to="attachments/")),
                ("number", models.CharField(max_length=50, null=True)),
                ("billing_address", models.TextField(null=True)),
                ("message", models.CharField(max_length=255, null=True)),
                ("message_on_statement", models.CharField(max_length=255, null=True)),
                (
                    "terms",
                    models.CharField(
                        choices=[
                            ("Due on receipt", "Due on receipt"),
                            ("Net 30", "Net 30"),
                            ("Net 60", "Net 60"),
                            ("Net 90", "Net 90"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("due_date", models.DateField(null=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Opened", "Opened"),
                            ("Sent", "Sent"),
                            ("Viewed", "Viewed"),
                            ("Paid", "Paid"),
                            ("Deposited", "Deposited"),
                            ("Cancelled", "Cancelled"),
                            ("Refund", "Refund"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("SKU", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="product_images/")),
                ("initial_quantity", models.IntegerField()),
                ("as_of_date", models.DateField()),
                ("reorder_point", models.DateField()),
                ("description", models.TextField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_inclusive", models.BooleanField(default=False)),
                ("purchasing_information", models.TextField(null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expense.expenseaccount",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expense.supplier",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tax",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(null=True)),
                ("cc", models.TextField(null=True)),
                ("bcc", models.TextField(null=True)),
                ("send_later", models.BooleanField(default=False)),
                ("date", models.DateField(null=True)),
                ("attachment", models.FileField(null=True, upload_to="attachments/")),
                ("reference_no", models.CharField(max_length=20, null=True)),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("memo", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Cancelled", "Cancelled")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.client",
                    ),
                ),
                (
                    "deposit_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("credit_card", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RefundReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(null=True)),
                ("cc", models.TextField(null=True)),
                ("bcc", models.TextField(null=True)),
                ("send_later", models.BooleanField(default=False)),
                ("date", models.DateField(null=True)),
                ("attachment", models.FileField(null=True, upload_to="attachments/")),
                ("number", models.CharField(max_length=50, null=True)),
                ("billing_address", models.TextField(null=True)),
                ("message", models.CharField(max_length=255, null=True)),
                ("message_on_statement", models.CharField(max_length=255, null=True)),
                (
                    "amount_refunded",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.client",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.paymentmethod",
                    ),
                ),
                (
                    "refund_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalesReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(null=True)),
                ("cc", models.TextField(null=True)),
                ("bcc", models.TextField(null=True)),
                ("send_later", models.BooleanField(default=False)),
                ("date", models.DateField(null=True)),
                ("attachment", models.FileField(null=True, upload_to="attachments/")),
                ("number", models.CharField(max_length=50, null=True)),
                ("billing_address", models.TextField(null=True)),
                ("message", models.CharField(max_length=255, null=True)),
                ("message_on_statement", models.CharField(max_length=255, null=True)),
                ("reference_no", models.CharField(max_length=20, null=True)),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.client",
                    ),
                ),
                (
                    "deposit_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.paymentmethod",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TagGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimeActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=255)),
                (
                    "billable",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("activity_time", models.TimeField(null=True)),
                ("description", models.TextField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.client",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.items",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accountant_pro.taggroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesReceiptPending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sales_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.salesreceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(null=True)),
                ("description", models.TextField(null=True)),
                ("quantity", models.PositiveIntegerField(null=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.items",
                    ),
                ),
                (
                    "sales_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.salesreceipt",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tax",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalesReceiptCompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sales_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.salesreceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesReceiptCancelled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sales_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.salesreceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesReceiptActive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sales_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.salesreceipt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="salesreceipt",
            name="tags",
            field=models.ManyToManyField(to="accountant_pro.tag"),
        ),
        migrations.CreateModel(
            name="RefundReceiptPending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "refund_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.refundreceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefundReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(null=True)),
                ("description", models.TextField(null=True)),
                ("quantity", models.PositiveIntegerField(null=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.items",
                    ),
                ),
                (
                    "refund_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.refundreceipt",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tax",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RefundReceiptCompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "refund_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.refundreceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefundReceiptCancelled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "refund_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.refundreceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefundReceiptActive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "refund_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.refundreceipt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="refundreceipt",
            name="tags",
            field=models.ManyToManyField(to="accountant_pro.tag"),
        ),
        migrations.CreateModel(
            name="PaymentPaid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentCancelled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.payment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accountant_pro.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accountant_pro.itemtype",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceViewed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceSent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoicePaid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(null=True)),
                ("description", models.TextField(null=True)),
                ("quantity", models.PositiveIntegerField(null=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.invoice",
                    ),
                ),
                (
                    "product_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.items",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tax",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceCancelled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.invoice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="tags",
            field=models.ManyToManyField(to="accountant_pro.tag"),
        ),
        migrations.CreateModel(
            name="EstimateRejected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "estimate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.estimate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstimatePending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "estimate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.estimate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstimateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(null=True)),
                ("description", models.TextField(null=True)),
                ("quantity", models.PositiveIntegerField(null=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.estimate",
                    ),
                ),
                (
                    "product_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.items",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tax",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EstimateClosed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "estimate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.estimate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstimateAccepted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "estimate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.estimate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="estimate",
            name="tags",
            field=models.ManyToManyField(to="accountant_pro.tag"),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("display_name", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("mobile", models.CharField(max_length=255, null=True)),
                ("street_address", models.TextField(null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("province", models.CharField(max_length=255, null=True)),
                ("postal_code", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                ("notes", models.TextField(null=True)),
                ("employee_id_number", models.CharField(max_length=255, null=True)),
                ("employee_id", models.CharField(max_length=255, null=True)),
                ("hire_date", models.DateField(null=True)),
                ("released_date", models.DateField(null=True)),
                ("billing_rate", models.CharField(max_length=255, null=True)),
                ("billable_by_default", models.BooleanField(default=False)),
                ("date_of_birth", models.DateField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Prefer not to answer", "Prefer not to answer"),
                            ("Male", "Male"),
                            ("Female", "Female"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DelayedCreditPending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "delayed_credit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.delayedcredit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DelayedCreditItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(null=True)),
                ("description", models.TextField(null=True)),
                ("quantity", models.PositiveIntegerField(null=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "delayed_credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.delayedcredit",
                    ),
                ),
                (
                    "product_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.items",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tax",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DelayedCreditCompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "delayed_credit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.delayedcredit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DelayedCreditCancelled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "delayed_credit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.delayedcredit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DelayedCreditActive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "delayed_credit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.delayedcredit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="delayedcredit",
            name="tags",
            field=models.ManyToManyField(to="accountant_pro.tag"),
        ),
        migrations.CreateModel(
            name="DelayedChargePending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "delayed_charge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.delayedcharge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DelayedChargeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(null=True)),
                ("description", models.TextField(null=True)),
                ("quantity", models.PositiveIntegerField(null=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "delayed_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.delayedcharge",
                    ),
                ),
                (
                    "product_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.items",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tax",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DelayedChargeCompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "delayed_charge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.delayedcharge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DelayedChargeCancelled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "delayed_charge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.delayedcharge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DelayedChargeActive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "delayed_charge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.delayedcharge",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="delayedcharge",
            name="tags",
            field=models.ManyToManyField(to="accountant_pro.tag"),
        ),
        migrations.CreateModel(
            name="CreditNotePending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "credit_note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.creditnote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditNoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(null=True)),
                ("description", models.TextField(null=True)),
                ("quantity", models.PositiveIntegerField(null=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "credit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.creditnote",
                    ),
                ),
                (
                    "product_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.items",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tax",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreditNoteCompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "credit_note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.creditnote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditNoteCancelled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "credit_note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.creditnote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditNoteActive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "credit_note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountant_pro.creditnote",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="creditnote",
            name="tags",
            field=models.ManyToManyField(to="accountant_pro.tag"),
        ),
        migrations.AddField(
            model_name="client",
            name="primary_payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountant_pro.paymentmethod",
            ),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_amount", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("iban", models.CharField(max_length=34)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companydetails.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubClient",
            fields=[
                (
                    "client_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accountant_pro.client",
                    ),
                ),
                ("bill_parent_customer", models.BooleanField(default=False)),
                (
                    "parent_client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent",
                        to="accountant_pro.client",
                    ),
                ),
            ],
            bases=("accountant_pro.client",),
        ),
    ]
