# Generated by Django 4.2.3 on 2024-03-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accountant_pro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="client",
            name="language_for_invoices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("English", "English"),
                    ("French", "French"),
                    ("Spanish", "Spanish"),
                    ("Italian", "Italian"),
                    ("Chinese (traditional)", "Chinese (traditional)"),
                    ("Portuguese (Brazil)", "Portuguese (Brazil)"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="primary_payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountant_pro.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="sales_form_delivery_options",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Print later", "Print later"),
                    ("Send later", "Send later"),
                    ("None", "None"),
                    ("Use company default", "Use company default"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Due on receipt", "Due on receipt"),
                    ("Net 30", "Net 30"),
                    ("Net 60", "Net 60"),
                    ("Net 90", "Net 90"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
