# Generated by Django 4.2.3 on 2024-03-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountant_pro", "0002_alter_client_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnote",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Due on receipt", "Due on receipt"),
                    ("Net 30", "Net 30"),
                    ("Net 60", "Net 60"),
                    ("Net 90", "Net 90"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="refundreceipt",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="salesreceipt",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
