# Generated by Django 4.2.3 on 2024-03-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companydetails", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(default="default", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(max_length=255)),
                ("suffix", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "customer_display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("fax", models.CharField(blank=True, max_length=20, null=True)),
                ("other", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("is_sub_customer", models.BooleanField(default=False)),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=255)),
                ("billing_address", models.CharField(max_length=255)),
                ("shipping_address", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="attachments/"),
                ),
                (
                    "primary_payment_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("terms", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sales_delivery_options",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "invoice_language",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sales_tax_registration",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("as_of_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Cost of sales", "Cost of sales"),
                            ("Expenses", "Expenses"),
                            ("Other expense", "Other expense"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("detail_type", models.CharField(max_length=100, null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
                ("is_sub_account", models.BooleanField(default=False)),
                (
                    "default_tax_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tax",
                    ),
                ),
                (
                    "parent_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("middle_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("suffix", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("mobile", models.CharField(max_length=255, null=True)),
                ("fax", models.CharField(max_length=255, null=True)),
                ("display_name", models.CharField(max_length=255, null=True)),
                ("other", models.CharField(max_length=255, null=True)),
                ("website", models.CharField(max_length=255, null=True)),
                ("street_address", models.TextField(null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("province", models.CharField(max_length=255, null=True)),
                ("postal_code", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                ("billing_rate", models.CharField(max_length=255, null=True)),
                (
                    "terms",
                    models.CharField(
                        choices=[
                            ("Due on receipt", "Due on receipt"),
                            ("Net 30", "Net 30"),
                            ("Net 60", "Net 60"),
                            ("Net 90", "Net 90"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("as_of", models.DateField(null=True)),
                ("notes", models.TextField(null=True)),
                ("account_no", models.CharField(max_length=255, null=True)),
                ("business_id", models.CharField(max_length=255, null=True)),
                ("attachment", models.FileField(null=True, upload_to="attachments/")),
                ("inactive", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_details",
                        to="companydetails.company",
                    ),
                ),
                (
                    "default_expense_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expense.expenseaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("description", models.TextField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expense.categories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_account",
                    models.CharField(default="Payment Account", max_length=255),
                ),
                ("payment_date", models.DateField(null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Cheque", "Cheque"),
                            ("Credit Card", "Credit Card"),
                            ("Direct Debit", "Direct Debit"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("tags", models.TextField(null=True)),
                ("memo", models.CharField(max_length=255, null=True)),
                ("attachment", models.FileField(null=True, upload_to="attachments/")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companydetails.currency",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expense.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(null=True)),
                ("description", models.TextField(null=True)),
                ("quantity", models.PositiveIntegerField(null=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax", models.BooleanField(default=False)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="expense.bills"
                    ),
                ),
            ],
        ),
    ]
