# Generated by Django 4.2.3 on 2024-03-23 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companydetails", "0001_initial"),
        ("accounts", "0001_initial"),
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billitems",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expense.bills",
            ),
        ),
        migrations.AlterField(
            model_name="bills",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="bills",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companydetails.company",
            ),
        ),
        migrations.AlterField(
            model_name="bills",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companydetails.currency",
            ),
        ),
        migrations.AlterField(
            model_name="bills",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expense.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="categoryitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expense.categories",
            ),
        ),
        migrations.AlterField(
            model_name="expenseaccount",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cost of sales", "Cost of sales"),
                    ("Expenses", "Expenses"),
                    ("Other expense", "Other expense"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expenseaccount",
            name="default_tax_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.tax",
            ),
        ),
        migrations.AlterField(
            model_name="expenseaccount",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expenseaccount",
            name="detail_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="expenseaccount",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="expenseaccount",
            name="parent_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="company",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_details",
                to="companydetails.company",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="default_expense_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expense.expenseaccount",
            ),
        ),
    ]
